"""initial migration

Revision ID: 2d5496a54cbd
Revises: 
Create Date: 2025-09-10 16:26:31.237301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5496a54cbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum'), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('aadhar_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('highest_education', sa.String(length=255), nullable=True),
    sa.Column('institute', sa.String(length=255), nullable=True),
    sa.Column('passing_year', sa.Integer(), nullable=True),
    sa.Column('education_status', sa.Enum('pursuing', 'passed_out', name='educationstatusenum'), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('resume_path', sa.String(length=255), nullable=True),
    sa.Column('preferred_job_role', sa.String(length=255), nullable=True),
    sa.Column('expected_salary', sa.Float(), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('linkedin_profile', sa.String(length=255), nullable=True),
    sa.Column('github_portfolio', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('aadhar_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_table('company_employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('HR', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'DRAFT', 'ARCHIVED', name='jobstatus'), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['company_employee.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_title'), ['title'], unique=False)

    op.create_table('application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REJECTED', 'SHORTLISTED', name='applicationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('application_progress',
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REJECTED', 'SHORTLISTED', name='applicationstatus'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['company_employee.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_table('email_log',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('REJECTION', 'INTERVIEW', 'OFFER', 'CUSTOM', name='emailtype'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_log')
    op.drop_table('application_progress')
    op.drop_table('application')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_title'))
        batch_op.drop_index(batch_op.f('ix_job_location'))

    op.drop_table('job')
    op.drop_table('company_employee')
    op.drop_table('candidate')
    # ### end Alembic commands ###
